### ISSUE TITLE
Feature: Game Lobby

### ISSUE THREAD

**Issue by philipdoucla** [CS-130-Winter-2024/balhalla#10]
## User Story
As a **developer**, I would like **a game lobby** so that **players can access the shop while they wait for matchmaking**.

## Detailed Description
While players wait for game to start, they will be put in a 3D lobby where they can access the Shop and Leaderboard features.

## Task List
- [x] Add switchable game state on server that allows different join behaviors depending on game state.
- [x] Add client-side spectate mode
- [x] Set spectate state for players who join during the middle of a game.
- [x] When switching from lobby to game, only bring players who have marked themselves as ready to play
- [x] Only players actively participating in a game should be able to be seen.

## Acceptance Criteria
- [x] Given **a shop button in the game lobby**, then **players can access the shop to purchase items**
- [x] Given **a leaderboard button in the game lobby**, then **players can access the player leaderboard**
- [x] Players can mark themselves as ready/unready to join the next dodgeball game
- [x] Players will spectate other players playing dodgeball while they are waiting in the lobby
